use alloc::string::String;
use alloc::vec::Vec;

use ngos_audio_translate::EncodedMix;
use ngos_game_compat_runtime::{
    AbiRoutingPlan, CompatTargetKind, GraphicsApi, GraphicsTranslationPlan, LoaderRoutingPlan,
};
use ngos_gfx_translate::EncodedFrame;
use ngos_input_translate::EncodedInput;

use crate::GameCompatLaneRuntime;

pub struct GameCompatSession {
    pub target: CompatTargetKind,
    pub title: String,
    pub slug: String,
    pub pid: u64,
    pub domain_id: usize,
    pub process_name: String,
    pub executable_path: String,
    pub working_dir: String,
    pub prefix_path: String,
    pub saves_path: String,
    pub cache_path: String,
    pub runtime_env_path: String,
    pub runtime_argv_path: String,
    pub runtime_channel_path: String,
    pub runtime_loader_path: String,
    pub runtime_abi_path: String,
    pub loader_preloads: Vec<String>,
    pub loader_dll_overrides: Vec<String>,
    pub loader_env_overrides: Vec<String>,
    pub loader_routing: LoaderRoutingPlan,
    pub abi_routing: AbiRoutingPlan,
    pub graphics_device_path: String,
    pub graphics_driver_path: String,
    pub graphics_source_api: GraphicsApi,
    pub graphics_translation: GraphicsTranslationPlan,
    pub graphics_profile: String,
    pub audio_device_path: String,
    pub audio_driver_path: String,
    pub audio_profile: String,
    pub input_device_path: String,
    pub input_driver_path: String,
    pub input_profile: String,
    pub last_frame_tag: Option<String>,
    pub last_graphics_queue: Option<String>,
    pub last_present_mode: Option<String>,
    pub last_completion_mode: Option<String>,
    pub last_completion_observed: Option<String>,
    pub last_frame_op_count: usize,
    pub last_frame_payload_bytes: usize,
    pub last_graphics_deep_ops: Option<String>,
    pub submitted_frames: u64,
    pub presented_frames: u64,
    pub last_presented: bool,
    pub pending_graphics_frames: Vec<EncodedFrame>,
    pub last_audio_stream_tag: Option<String>,
    pub last_audio_route: Option<String>,
    pub last_audio_latency_mode: Option<String>,
    pub last_audio_spatialization: Option<String>,
    pub last_audio_completion_mode: Option<String>,
    pub last_audio_completion_observed: Option<String>,
    pub last_audio_op_count: usize,
    pub last_audio_payload_bytes: usize,
    pub submitted_audio_batches: u64,
    pub last_audio_invoke_token: Option<usize>,
    pub pending_audio_batches: Vec<EncodedMix>,
    pub last_input_frame_tag: Option<String>,
    pub last_input_family: Option<String>,
    pub last_input_layout: Option<String>,
    pub last_input_key_table: Option<String>,
    pub last_pointer_capture: Option<String>,
    pub last_input_delivery_mode: Option<String>,
    pub last_input_delivery_observed: Option<String>,
    pub last_input_op_count: usize,
    pub last_input_payload_bytes: usize,
    pub submitted_input_batches: u64,
    pub last_input_invoke_token: Option<usize>,
    pub pending_input_batches: Vec<EncodedInput>,
    pub lanes: Vec<GameCompatLaneRuntime>,
    pub stopped: bool,
    pub exit_code: Option<i32>,
}
